---
functional:
  - Сайт должен иметь авторизацию
  - Пользователь должен иметь возможность создать игру
  - Игра дожна отображаться как доступная к подключению у других пользователей
  - Пользователь должен иметь возможность подключиться к созданной игре
  - Пользователи в игре должны видеть свой свой редактор кода и редактор кода своего соперника
  - Редактор соперника отображается в режиме реального времени
  - Пользователидолжны иметь возможность проверить свое решение неограниченное колличество раз
  - При отключении одного из пользователь другой должен иметь возможность продолжать игру
  - При отключении пользователя он должен иметь возможность подключиться обратно к игре пока она не закончена
non-functional:
  - Сайт должен быть разработан с учетом удобства использования
  - Сайт должен быть  оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
implicit:
  - Пользователь должен иметь возможность создать игру против бота
  - Пользователь должен иметь возможность создать игру против определёного пользователя
  - Пользователь должен иметь возможность содавать турниры против множетсва других пользователей
