---
functional:
  - Сайт должен иметь авторизацию
  - Пользователь должен иметь возможность создать игру
  - Игра дожна отображаться как доступная к подключению у других пользователей
  - Пользователь должен иметь возможность подключиться к созданной игре
  - Пользователи в игре должны видеть свой свой редактор кода и редактор кода своего соперника
  - Редактор соперника отображается в режиме реального времени
  - Пользователидолжны иметь возможность проверить свое решение неограниченное колличество раз
  - При отключении одного из пользователь другой должен иметь возможность продолжать игру
  - При отключении пользователя он должен иметь возможность подключиться обратно к игре пока она не закончена
  - Когда один из игроков находит верное решение обоим игрокам высвечивается модальное окно где написано кто является победителем этой игры
  - Пользователь победитель должен иметь возможность выйти из игры
  - Пользователь победитель не должен иметь возможность заново проверить своё решение
  - Пользователь победитель должен иметь возможность остаться в игре.
  - Проигравший пользователь должен иметь возможность выйти из игры
  - Проигравший пользователь должен иметь возможность остаться в матче и доиграть игру
non-functional:
  - Сайт должен быть разработан с учетом удобства использования
  - Сайт должен быть  оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика 
  - Когда оба игрока вышли игра должа считать законченой
  - Законченные игры должны удаляться из памяти
implicit:
  - Пользователь должен иметь возможность создать игру против бота
  - Пользователь должен иметь возможность создать игру против определёного пользователя
  - Пользователь должен иметь возможность содавать турниры против множетсва других пользователей
